apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-blog-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-blog=ghcr.io/chc3954/my-blog-with-rails
    argocd-image-updater.argoproj.io/my-blog.update-strategy: latest
    argocd-image-updater.argoproj.io/my-blog.allow-tags: regexp:^v[0-9]+$
    argocd-image-updater.argoproj.io/my-blog.pull-secret: my-blog/ghcr-secrets
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/chc3954/my-blog-with-rails.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: my-blog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
