apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-blog-ingress
  namespace: my-blog
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: my-blog.local # Change this to your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-blog-service
                port:
                  number: 80
