apiVersion: v1
kind: Service
metadata:
  name: my-blog-service
  namespace: my-blog
spec:
  selector:
    app: my-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
